platform :ios, '15.6'

target 'weatherApp' do
  use_frameworks! :linkage => :static

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'

  target 'weatherAppTests' do
    inherit! :search_paths
  end

  target 'weatherAppUITests' do
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
    end
  end
end
