# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'weatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weatherApp
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'
  target 'weatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherAppUITests' do
    # Pods for testing
  end

end
